/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TROOEXTENDEDBINDING
#define TROOEXTENDEDBINDING

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooSetProxy.h"
#include "RooAbsPdf.h"
 
class TRooExtendedBinding : public RooAbsReal {
public:
  TRooExtendedBinding() {} ; 
  TRooExtendedBinding(const char *name, const char *title, RooAbsPdf& _pdf, const RooArgSet& _nset);
  TRooExtendedBinding(const TRooExtendedBinding& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new TRooExtendedBinding(*this,newname); }
  inline virtual ~TRooExtendedBinding() { }

protected:

  RooRealProxy pdf ;
  RooSetProxy nset ;
  
  Double_t evaluate() const ;

private:

  ClassDef(TRooExtendedBinding,1) // Your description goes here...
};
 
#endif
